axa-group/nlp.js

lib/nlp/nlp-manager.js
Before,  the rows were composed by zeros and ones. To reduce the size of the resulting .npl file, now the rows are an array with the positions of the elements equals to one.
```js
// See this example
[0, 0, 1, 0 , 0, 1, 1, 1, 0, 0] => [2, 5, 6, 7]
```
The load function has been adapted to be able to process the new format into the zeros and ones format that the nlp manager needs.
=> feat: reduce .nlp files size

lib/ner/trim-named-entity.js, package-lock.json, test/ner/ner-manager.test.js
It adds an skip property to the options of the conditions at Trim Named Entities. That way, some results are blacklisted. 
Reason to have that: In the utterance "I want to travel from Madrid to Barcelona", if you want to extract a from location and a to location that works also for "I want to travel to Barcelona from Madrid", you can add:
From: between from and to or last after from
To: between to and from or last after to
The problem is that the "to" condition extract also the "travel" word because is between a "to" and a "from". Skipping "travel" in the between condition works, and the result is the expected.
=> feat: Add skip results at Trim Named Entities conditions

examples/nlu-benchmark/index.js
Adds await to `manager.train()` so the process starts after training ends. This was impacting
benchmarking scores
closes #81
=> fix: fix missing await in NLU-Benchmark

lib/language/languages.json, package.json
Resolves #99
Some languages are not working with language detection that should. The problem seems to be [`franc`](https://github.com/wooorm/franc) is using one set of language codes and this package is using another.
**Note:** I didn't go through all the languages; I only checked the top ~30.
=> :bug: fix: language detection not working for some languages

.npmignore
Hi,
First, thank you for this awesome library! 
I installed it locally using NPM and realized that the module was taking **60Mb** on my disk. 
By looking at the folder structure, it seems that many folders (screenshots, documentation, .vscode, .github) are uploaded to NPM.
Here is the folder structure of the module uploaded to NPM:
So I checked the .npmignore, and indeed it was not working properly.
Here is a proposal of a fix in this PR.
Note: 
- I added the `coverage`, `test`, `.github` and `.vscode` folder. I don't think there are relevant when running the library.
- I added the `dist` folder to the .npmignore too, because it's a duplicate of the code and it seems that the package.json is calling `lib/index.js` as the main file, not the bundle one. Tell me if you think it's ok. 
This …
=> Fix .npmignore file

docs/ner-manager.md
It seems the default threshold value has changed since the NER manager documentation has been written. The current default value is now `0.8` (cf. [lib/ner/ner-manager.js#L52](https://github.com/axa-group/nlp.js/blob/master/lib/ner/ner-manager.js#L52)).
=> docs(ner-manager): change default threshold to 0.8

lib/nlg/nlg-manager.js, lib/util/similar-search.js, test/ner/ner-manager.test.js
Chinese entity extraction was not working properly due to the fact that the language does not contains whitespaces. Now, when getting words positions, first the top script (latin, cmn, ...) of each character is extracted, and if the character is cmn (chinese charset) then the character is considered a full word.
=> Fix Chinese Entity Extraction

lib/ner/ner-manager.js, test/ner/ner-manager.test.js
ner-manager.generateEntityUtterance() was returning wrong utterances.
=> Fix ner-manager.generateEntityUtterance

README.md, docs/ner-manager.md, docs/slot-filling.md, lib/ner/ner-manager.js, test/ner/ner-manager.test.js
Support slot filling with more than one entity with the same name by providing "numbered entities". E.g. "I saw %hero_1% and %hero_2% fighting together".
=> New feature: Numbered entities

lib/nlp/stemmers/base-stemmer.js
BaseStemmer.js imports all tokenizers, when it only needs TreebankWordTokenizer. Some of the tokenizers, like Japanese & Chinese, has special requirements, and the PR allows not importing them when they are not necessary
=> build: finer grain import in BaseStemmer to reduce dependencies

lib/ner/ner-recognizer.js
Added support for the datetimerange response from Microsoft Recognizers. This is triggered when a user says something like "tomorrow morning". I was working on adding tests for this but the date/time parsing doesn't currently support using a reference time. This should be added at a later time.
=> fix: Extended NER to support datetimerange

lib/classifiers/neural-network.js
Use performance.now instead of process.hrtime to have browser compatibility
=> feat: use performance.now instead of process.hrtime

CHANGELOG.md, package-lock.json, package.json
- Traverse for handlebars, so answers now can be arrays or objects
- Automatic stemmer: is able to learn rules from languages without stemmer when the languages are inflected.
- Tests of the automatic stemmer in polish 
- Spell checking: now users can write with small typos
- Changelog
- Portuguese sentiment analysis
- Contributor pictures to the readme
- Bengali sentiment analysis
- Faster Levenshtein implementation
- Now the browser version is generated with terser
- Extended NER to support datetimerange
- Sort classifications in the NER manager
- Use performance.now instead of process.hrtime for browser compatibility
=> build: version 3.10.0

lib/nlp/stemmers/spanish-stemmer.js, test/nlp/stemmers/spanish-stemmer.test.js
added unit test for Spanish.
"trepadora" and "considerara" are still not correctly stemmed
SpanishStemmer was not compatible with AggressiveTokenizerEs, because the latter removes the accents, and the former was expecting them
=> fix: remove accents from SpanishStemmer

lib/ner/regex-named-entity.js, test/ner/regex-named-entity.test.js
Passing a regex without 'g' flag to addRegex results in an infinite loop. This checks that and fix the incoming regex.
=> fix(regex): check global flag is present

.eslintrc, lib/nlg/action-manager.js, lib/nlp/nlp-manager.js, test/nlg/action-manager.test.js, test/nlp/nlp-manager.test.js
Implemented logic to process actions. It also works with async actions.
A map of actions can be set during the init of NlpManager and after is possible to relate intent with action passing custom parameters.
It's also possible to reuse the same action with different parameters in the same intent.
Example of usage:
```
const manager = new NlpManager({
languages: ['en'],
action: { // I suggest to call it actionMap
action1: (input, ...parameters) => {
return `(${input}#${parameters.join(',')})`;
},
action2: (input, ...parameters) => {
return `[${input}#${parameters.join(',')}]`;
},
},
});
manager.addDocument('en', 'goodbye for now', 'greetings.bye');
manager.addDocument('en', 'bye bye take care', 'greetings.bye');
manager.addDocument('en', 'hello', 'greetings.hello'); …
```
=> feat(actions): add logic to process actions

lib/nlu/base-nlu.js
When trying to make a model using nlp.js-app and to export it using spellCheck, I found that exporting and importing left out the spellCheckDistance property from base-nlu.
I tried the fix locally and it works so yeah :D
=> Make spellchecker importable/exportable

packages/ner/src/extractor-enum.js, packages/ner/test/extractor-enum.test.js
Don't concat the next word if doing it will never match with
the first word
Making the most of the threshold argument of ExtractorEnum.getBestSubstringList, it is possible to implement a simple optimization which significally reduces the cost of the function. 
The algorithm checks the match of the 2nd string on each subsequence of words from the 1st string. The optimization consists on stop enlarging the subsequence once it's impossible that any match potentially obtained extending it with the next word requires the 1st word of the subsequence. At this point it's safe to shift right the first word of the 1st string subsequence
=> feat: optimize ExtractorEnum.getBestSubstringList

packages/ner/src/reduce-edges.js
Solves https://github.com/axa-group/nlp.js/issues/388
When a text matches twice an entity and there is an overlapping, chose the biggest.
Example:
"good" and "very good". The sentence "This is very good" will match both, as "good" is contained into "very good" then the edge matching "good" is discarded.
=> feat: reduce enum edges interesections choosing biggest one

packages/lang-es/test/stemmer-es.test.js, packages/lang-pt/test/stemmer-pt.test.js, packages/lang-pt/test/tokenizer-pt.test.js
Portuguese tokenizer requires to split by "-" for words like "disse-me". However, it should not split words ending in "-" followed by a number, for words like "covid-19"
=> feat: TokenizerPt not to split words like covid-19

packages/nlu/src/domain-manager.js
When no intent is returned put the default domain instead of crashing.
This should solve https://github.com/axa-group/nlp.js/issues/416
=> fix: don't crash if no intent is returned

package-lock.json, packages/ner/src/reduce-edges.js, packages/nlu/src/domain-manager.js
When using stem dict, the intent was classified twice.
Reduce edges now takes into account that the developer can introduce the same text several times
=> fix: stem dict replicates intent. Reduce edges also replicates entity.

packages/ner/src/ner.js
Fixes #431 by serializing `RegExp` objects using the `toString()` method when saving, but also using the `Ner.str2regex()` static method to parse stringified regex rules when loading a model.
=> Serialize regex rules by using toString

packages/neural/src/neural-network.js
Don't calculate deltas when the current perceptron error is 0
=> feat: remove calculate deltas when no current error was found

package-lock.json, packages/request/package-lock.json, packages/request/package.json
Avoid request patching https://github.com/TooTallNate/node-agent-base/issues/38
This bumps the version of `https-proxy-agent`. The usage of `https-proxy-agent` has nothing out of the ordinary, so this should not hurt compatibility.
=> Bump https-proxy-agent version

packages/ner/src/reduce-edges.js
At discard edges the order or the edges now is taken into account. As the array of edges is not sorted from best to worst, then sorting 2 by 2 is the best option here.
It fixes https://github.com/axa-group/nlp.js/issues/460
=> fix: reduce edges now order edges before processing

packages/directline-connector/src/directline-controller.js
When the channel is emulator, then return the NLP information in the Activitity of the Directline.
=> feat: return nlp information in Directline API

packages/api-auth-jwt/package-lock.json, packages/builtin-microsoft/package-lock.json, packages/neural-worker/src/neural-network.js, packages/neural/src/neural-network.js
Related issue #490
`import` and `export` did not work as expected for my model. After debugging for a bit, I realized that the order of features is incorrect when there are numeral features. \
The reason for that is, that `Object.keys` orders numbers first.
In `NeuralNetwork` (both packages) I've made the following changes:
1. `toJSON`: instead of using `Object.keys` to get the features, I sort the object's entries by it's value and then return it's key.
2. `fromJSON`: instead of using `toHash` which uses `Object.keys` under the hood, I iterate the features and directly set them. 
These changes guarantee that a numeral feature is at the correct position in `inputLookup`.
If you have any questions, just let me know.
PS: Thanks for the nice library!
=> 🐛 Fix bug for numeral features when exporting/importing

packages/core/src/tokenizer.js, packages/nlp/src/nlp.js, packages/nlu/src/nlu.js, packages/slot/src/slot-manager.js
Improve performance by:
- Use caches, mainly on the prepare method of nlu and tokenizers. Those caches are automatically cleaned to avoid being a memory leak.
- Sentiment analysis can be disabled in the NLP options.
- Optional Utterance and NER is not triggered if no entities where defined to intents (at the slot manager).
=> feat: improve performance by cache and avoid ner if no entity is defined

packages/msbf-connector/src/msbf-connector.js
onHear event of MSBF connector must be awaited
=> fix: await onHear on MSBF connector

packages/api-auth-jwt/src/api-auth-jwt.js, packages/api-auth-jwt/test/api-auth-jwt.test.js
Hi,
When I create and run a test Bot using the `ApiAuthJwt` plugin, I get the following error:
```sh
> node index.js
...
(node:19371) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'plugins' of undefined
at ApiAuthJwt.register (/Users/nXXX/workspace/nlpjs-auth-test/node_modules/@nlpjs/api-auth-jwt/src/api-auth-jwt.js:37:15)
at Container.use (/Users/nXXX/workspace/nlpjs-auth-test/node_modules/@nlpjs/core/src/container.js:346:16)
at containerBootstrap (/Users/nXXX/workspace/nlpjs-auth-test/node_modules/@nlpjs/core-loader/src/container-bootstrap.js:233:20)
at Dock.createContainer (/Users/nXXX/workspace/nlpjs-auth-test/node_modules/@nlpjs/core-loader/src/dock.js:68:25)
at Dock.terraform (/Users/nXXX/workspace/nlpjs-auth-test/node_modules/@nlpjs/core-loader/src/dock.js:113:41 …
```
=> fix: cannot read property of undefined at ApiAuthJwt.register

packages/lang-cs/src/stemmer-cs.js
A czech word should be at least 5 chars length to be stemmed
=> feat: min length before stemming a czech word

packages/lang-tr/src/stemmer-tr.js, packages/lang-tr/test/stemmer-tr.test.js
Turkish Stemmer was not working because it was overriding "stem" instead of "innerStem"
=> fix: StemmerTr was overriding the wrong method

packages/similarity/src/cosine-similarity.js, packages/similarity/src/index.js, packages/similarity/test/cosine-similarity.test.js
In the similarity package, I think it could be useful to include a cosine similarity method. Put together with tokenizer & stemmer, can help to get a factor of similarity between two sentences (I'll add similarity of set of sentences in a different PR).
Using right packages it can be used to compare sentences in several locales available in nlp.js.
Tests set is also included in the PR :)
Example of usage with latin characters (**without external deps**):
test.js
```
const { dockStart } = require('@nlpjs/basic');
const { CosineSimilarity } = require('@nlpjs/similarity');
(async () => {
const cosineSimilarityTools = new CosineSimilarity();
console.log(cosineSimilarityTools.similarity('hello world', 'hello bye'));
})();
```
Example of usage with chinese & japanese characters (**extra …
=> feat: add cosine similarity

packages/lang-ja/src/stemmer-ja.js, packages/nlp/src/nlp.js
- Fix japanese stemmer to load dictionaries
- Add post-fill from stemmers in NLP
=> fix: japanese stemmer now read correctly the dictionary

packages/evaluator/src/compile.js
When the evaluator have variables evaluated to falsy (empty string, 0,...) then the variable was not replaced.
=> fix: Evaluator falsy values do not process correctly texts

.gitignore, package-lock.json, package.json, packages/express-api-server/package-lock.json, packages/express-api-server/package.json, packages/express-api-server/src/express-api-app.js, packages/express-api-server/src/express-api-server.js, packages/express-api-server/test/express-api-app.test.js, packages/express-api-server/test/express-api-server.test.js
Hi @jesus-seijas-sp,
As discussed in #580, I've:
* Split the `ExpressApiServer` class in two;
* Add the `supertest` dev dependency;
* Added unit tests for the two classes;
I hope this helps.
Yours,
Nick
=> Express api server tests

packages/lang-bn/src/sentiment/sentiment_bn.js, packages/lang-ca/src/sentiment/sentiment_ca.js, packages/lang-da/src/sentiment/sentiment_da.js, packages/lang-de/src/sentiment/sentiment_de.js, packages/lang-en/src/sentiment/sentiment_en.js, packages/lang-es/src/sentiment/sentiment_es.js, packages/lang-eu/src/sentiment/sentiment_eu.js, packages/lang-fi/src/sentiment/sentiment_fi.js, packages/lang-fr/src/sentiment/sentiment_fr.js, packages/lang-gl/src/sentiment/sentiment_gl.js, packages/lang-it/src/sentiment/sentiment_it.js, packages/lang-nl/src/sentiment/sentiment_nl.js, packages/lang-pt/src/sentiment/sentiment_pt.js, packages/lang-ru/src/sentiment/sentiment_ru.js, packages/sentiment/src/sentiment-analyzer.js
Sentiment analysys can use non stemmed dictionaries
=> feaat: sentiment dictionaries can be non stemmed

packages/utils/test/progress-bar.test.js
fix failing progress bar tests: sometimes some tests take more than 0.0 seconds
=> fix: progress bar tests sometimes takes more than 0.0 seconds

packages/core-loader/src/plugin-information.json, packages/mongodb-adapter/src/mongodb-adapter.js
Register MongodbAdapter as plugin
=> feat: mongodb adapter now is a plugin that registers as database

examples/13-languages/corpora/corpus-en.json, packages/sentiment/src/sentiment-analyzer.js
Default "stemmed" for sentiment dictionaries must be false
=> fix: default stemmed for sentiment dictionaries must be false

examples/13-languages/measure-corpus.js, packages/ner/src/extractor-trim.js, packages/ner/test/extractor-trim.test.js
Fix trim ner when word match at position 0
=> fix: trim match when word is at position 0

packages/database/src/memory-adapter.js
check if length of conditionKeys is 0.
=> fix: memory adapter conditionKeys check length is 0

packages/builtin-compromise/test/compromise.test.js, packages/ner/src/extractor-enum.js, packages/ner/src/extractor-regex.js, packages/ner/src/extractor-trim.js, packages/nlp/src/nlp.js, packages/nlp/test/nlp.test.js
I would like to be able to use the corpus file format to import entities that use a combination of options, regular expressions and trims.
I suggest to alter the addEntities function to allow importing an entity with the following format
"entities": {
"chessMoveFrom": {
options:['a','b'],
regex: ['[\d]'] ,
trim: [{position:'between',words:['from','to'],options:{caseInsensitive:true}]
}
----------------------------------------------------------
In the process of testing the changes I made to addEntities I noticed that while an array of disparate rule types can be added under a single entity key, the extractors were throwing errors when presented with rules that didn't match the expected structure. 
Where disparate rule types are added to a single entity, the type is set appropriately for …
=> multiple enum,regex,trim rules per entity

packages/utils/src/is-gibberish.js, packages/utils/test/gibberish.test.js
Improvie gibberish detection algorithm:
- Vowel freq and consonant freq are now replaced by a vowel over consonant ratio
- Words with less than 6 characters are considered good
- Y is now a vowel
=> fix: improve gibberish score

packages/utils/src/is-gibberish.js, packages/utils/test/gibberish.test.js
Avoid Log(0) in deviation calculation of gibberish score
=> fix: avoid log(0) in deviation

packages/utils/src/is-gibberish.js, packages/utils/test/gibberish.test.js
Avoid use vowel/consontant ratio as a devaition, because is not in [0, 1] range
=> fix: gibberish detection, no deviation of vowel over consonant

packages/bot/src/bot.js, packages/bot/src/dialog-manager.js
With the current version, when you call accidentally a dialog that doesn't exist in the flows, the client gets stuck without giving any answer or feedback. With this change, the dialog name will be understood as a text to say instead of calling to beginDialog.
I think this facilitates error detection during development and enables to answer with a text starting with / that is not a dialog.
=> feat: add way to handle cases when dialog doesnt exist

packages/bot/src/bot.js, packages/nlp/src/context-manager.js
In the current implementation there's no direct way to reset flows & contexts before calling `bot.loadScript(...)` with new content from the application. With this PR we cover both cases. It's also possible to remove context for a single conversation.
=> feat: add reset flows & contexts

packages/nlp/src/context-manager.js
With the current implementation, using a database to get & set context, using database.save introduced more than one version of the context for the same conversation. Flows stopped to work on that point because dialogStack remains inconsistent.
I fix this using database.update with upsert set to true, to keep a single source of truth. I also add an event emission `onCtxUpdate` to be able to listen for context updates, useful for example to store dialog stack changes from the application.
=> fix: set ctx using database

packages/core/src/base-stemmer.js
Ran across this trying to train my data. I didn't look into why `stem` was returning undefined. This is just a small patch.
=> fix: errors on BaseStemmer.stem returning undefined

package-lock.json, packages/bot/src/bot.js, packages/bot/src/dialog-manager.js
Always that a session.say happen, we have to send the context so string templating is done.
=> fix: send context always that a session.say is executed

packages/bot/src/bot.js, packages/bot/test/script4.dlg
Bot **set** does not asume now that input is string. 
Breaking change: now to set a variable with an string value, it must be quoted
=> feat: set variable don't asume that input is string

packages/rest-connector/src/rest-connector.js
At REST connector, activity is created. It should include an address with conversation id for correct context retrieval.
=> fix: address with conversation id is mandatory in activity

packages/bot/src/bot.js
When validation retries was 0 there was a fallback to number 2.
=> fix: when retries is 0 it was identified as 2

packages/ner/src/extractor-enum.js
Bug when NER threshold is 1 and there is a regex rule.
https://github.com/axa-group/nlp.js/issues/778
=> fix: don't crash when NER threshold is 1 and there are regex

packages/rest-connector/src/rest-connector.js
Get locale at /rest/token of rest-connector
=> feat: locale can be set at rest connector token creation

packages/nlu/src/nlu-neural.js
When there is no perceptron at the dense network, it returned undefined. The problem is that this cause classifications[0] to not exists. Then by default if undefined is returned, then return { None: 1 }
=> feat: return None classification when no perceptron at network

packages/nlu/src/nlu.js, packages/nlu/test/domain-manager.test.js, packages/nlu/test/nlu.test.js
Unable to complete `lerna bootstrap` due to some network reasons in my environment, only tests in `packages/nlu` have been run.
```js
(async () => {
const container = await containerBootstrap();
const manager = new DomainManager({ container, trainByDomain: false });
await manager.train();
const actual = await manager.process('');
// will throw "Error at nlu.prepare: expected a text but received [object Object]"
// which is confusing and apparently not intended.
console.log(actual);
})();
```
=> fix(nlu): can handle zero-byte string in Nlu#prepare

docs/v4/language-support.md
I have only edited the markdown for the supported languages table that was broken on some languages (and breaking every line after them). No tests needed.
Lines for the following languages were broken, and messing with the table markdown:
- English
- Indonesian
- Italian
- Spanish
=> Fix table markdown formatting.

packages/bot/src/dialog-parse.js
When having a dialog which includes a `say` action text within brackets, the text inside brackets is removed and assumed to be settings of the `say` action.
The [trimBetween()](https://github.com/axa-group/nlp.js/blob/master/packages/bot/src/dialog-parse.js#L37) function parses everything inside brackets as settings:
```
dialog my_dialog
say Something (clarifying) whatever
```
Would be parsed as the following actions:
```json
[
{
"type": "dialog",
"srcLine": "dialog my_dialog",
"line": "my_dialog",
"condition": "",
"settings": ""
},
{
"type": "say",
"srcLine": "say Something (clarifying) whatever",
"line": "Something  whatever",
"condition": "",
"settings": "clarifying"
}
]
```
=> fix #1081: Allow parenthesis in `say` actions

packages/lang-de/src/sentiment/negations_de.json
"Keinen" is the accusative case of kein.
In German language there're 3 genera with corresponding forms:
female: keine - keine - keiner - keiner
neutral: kein - kein - keinem - keines
Male: kein - KEINEN - keinem - keines
So I added the only missing one.
=> Add the missing word "keinen"

packages/nlu/src/nlu.js
If you are using a single instance of the `Nlu` class and loading different models using `fromJSON` only the first configuration will work for intent classification. This is because the `convertToArray` function keeps the same `intentsArr` built from the keys in the `intents` property. Loading from json resets the `intents` property but not `intentsArr`. If you change models using fromJSON the `intentsArr` from the first model will stick around an you'll always get no intent classifications. 
This PR resets the `intentsArr` property to the `intents` keys every time you load from JSON.
=> Fix intents array on json load

packages/nlg/src/action-manager.js, packages/nlg/src/nlg-manager.js, packages/nlp/src/context-manager.js, packages/nlp/src/nlp.js, packages/nlp/test/nlp.test.js, packages/nlp/test/template-mock.js, packages/slot/src/slot-manager.js, packages/slot/test/slot-manager.test.js
I currently can not intall the project because of issues reported with some used tarballs. WHen I execute the tests eslint reports 16 errors and 47 warnings all over the place. I can try to fix them, but So I decided to not add new tests. Please tell me if needed
While checking out slot Filling with v4 I encountered several unexpected topics I solve in this PR:
* When using slot filling there was a "srcAnswer" property added to the result, but this was not processed like the other answers by nlg. The PR adds that
* the nlg text rendering had an issue that when a contact was set that then "optional answer text" was not processed because done but ignored and original text was used. PR also addresses that
* The answers were rendered before the slot filling filled relevant entities. This PR …
=> feat: Optimize slot finding answer processing

packages/core/src/stemmer.js
Because of wrongly set brackets the "input.locale" was in fact never used as soon as also a settings locale was set -  and if nothing in settings it was falling back to "en".
This PR adjusts the brackets in the condition.
This was coming from a issue in the repository, but I do not know which anymore (sorry)
I decided to not adjust tests because it is obvious to mem that the brackets are wrong.
=> fix: locale of import should have precedence over settings locale

packages/bot/src/dialog-parse.js
Replace regex test command for string match to fix an issue with global regex flag. 
Quoting [mdm documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test) about this topic:
```As with exec() (or in combination with it), test() called multiple times on the same global regular expression instance will advance past the previous match.```
This stateful behaviour generates an error when using the same regex for testing multiple lines.
=> fix: translations wrong link regex search

packages/bot/test/dialog-parse.test.js
Unit testing for #1238. 
Testing several translations with links in the same text. Regex should not be affected by previous parsing.
=> test: parsing consecutive translations with links with regex

packages/ner/src/extractor-enum.js, packages/ner/src/extractor-trim.js, packages/ner/test/extractor-enum.test.js
This PR is a fix for an issue reported in the repository (need to check if I can find it again). The problem is that the entity extraction was using normal whitespaces till now and this is not working in languages like japanese which is not using whitespaces.
So this PR introduce the usage of the tokenizer to splitup the text into words and then do the entity extraction based on this text. It also has the neded logic to correctly map the "positions" then back to the original text, so that the positions contained in the entity details are correct
=> feat: use tokenizers to split words before doing entity detection

packages/nlp/src/nlp.js, packages/nlp/test/nlp.test.js, packages/nlu/src/domain-manager.js
This PR adds a method nlp.addAdditionalEnumEntityUtterances() which uses the already registered sentences and uses the defined enum entities to iterate throigh all combinations nd add these as sentences. This should help in training because improves word matching to allow to better select the correct intent.
It was a done for an issue in repository.
Note: because the PR on branch #1221 adjusts/fix the behavior when matching entities I needed to tweak the tests here. Depending on merge order tests will break or we need to merge master in here - or we fix tests after merging. I added todos
=> Use Enum Entities to enhance the sentences to train

packages/ner/src/ner.js, packages/ner/test/ner.test.js
Some ESLint warnings, but same amount as in `master`:
All tests pass:
Fixes a bug with Named Entity Recognition where it doesn't deserialize regular expressions from JSON properly for all rule types.
A possible alternative to the fixes in https://github.com/axa-group/nlp.js/pull/1292 and https://github.com/axa-group/nlp.js/pull/1278 (though I'm not 100% sure if it covers those use cases).
=> fix(ner): deserialize regex from JSON
