axa-group/nlp.js

- examples/console-bot/index.js
- examples/console-bot/train-nlp.js
- lib/ner/ner-manager.js
- lib/nlp/nlp-manager.js
- lib/nlp/nlp-util.js
- lib/util/similar-search.js
- package-lock.json
- package.json
- test/ner/builtins/number-builtin.test.js
- test/ner/enum-named-entity.test.js
- test/ner/ner-manager.test.js
- test/nlp/nlp-manager.test.js
- test/nlp/nlp-util.test.js
- test/util/similar_search.test.js
Adding default builtin entity extraction.
> feat: default builtins for several languages

- README.md
- [N/A] I have run `npm test` locally and all tests are passing.
Just fixing a spelling typo on README.md
> Fixing a typo on README.md

- .gitignore
- docs/example-of-use.md
- docs/ner-manager.md
- docs/nlp-manager.md
- docs/sentiment-analysis.md
- lib/ner/ner-manager.js
- lib/nlp/nlp-manager.js
- lib/recognizer/recognizer.js
- lib/sentiment/sentiment-manager.js
- test/ner/builtins/builtin.test.js
- test/ner/ner-manager.test.js
- test/nlp/nlp-manager.test.js
- test/recognizer/recognizer.test.js
- test/sentiment/sentiment-analyzer.test.js
- test/sentiment/sentiment-manager.test.js
> Async interface #22

- docs/nlp-manager.md
- lib/nlp/nlp-manager.js
- test/nlp/nlp-manager.test.js
Add option for NLPManager which allow modifying `.process` output format
> JSON transformations

- docs/ner-manager.md
- lib/index.js
- lib/ner/index.js
- lib/ner/ner-manager.js
- lib/ner/trim-named-entity.js
- package-lock.json
- test/ner/ner-manager.test.js
- test/ner/trim-named.entity.test.js
> feat: Trim Named Entity

- lib/nlp/nlp-manager.js
- test/nlp/nlp-manager.test.js
Solves https://github.com/axa-group/nlp.js/issues/23
> feat: Domains

- lib/ner/ner-manager.js
- lib/ner/trim-named-entity.js
- lib/nlp/nlp-manager.js
- package-lock.json
- test/nlp/nlp-manager.test.js
Solves https://github.com/axa-group/nlp.js/issues/30
> feat: Load and Save Trim Named Entities

- docs/language-support.md
- lib/nlp/nlp-util.js
- lib/nlp/stemmers/base-stemmer.js
- lib/nlp/stemmers/catalan-stemmer.js
- test/nlp/nlp-util.test.js
> feat: Catalan language

- lib/nlp/nlp-util.js
- lib/nlp/stemmers/basque-stemmer.js
- test/nlp/nlp-util.test.js
> feat: Basque stemmer

- lib/nlp/nlp-util.js
- lib/nlp/stemmers/irish-stemmer.js
- test/nlp/nlp-util.test.js
> feat: Irish Stemmer

- lib/nlp/nlp-util.js
- lib/nlp/stemmers/slovene-stemmer.js
- test/nlp/nlp-util.test.js
> feat: Slovene Stemmer

- lib/nlp/nlp-util.js
- lib/nlp/stemmers/armenian-stemmer.js
- test/nlp/nlp-util.test.js
> feat: Armenian Stemmer

- lib/nlp/nlp-util.js
- lib/nlp/stemmers/tamil-stemmer.js
- test/nlp/nlp-util.test.js
> feature: Tamil Stemmer

- docs/nlp-classifier.md
This pull request adds Tamil to the nlp-classifier language list. Addresses #60
> docs: Adding Tamil (ta) to the nlp-classifier.md list

- docs/language-support.md
just updated documentation as requested on issue #61.
> updated Builtin Entity Extraction on the language-support.md file

- examples/console-bot/index.js
- examples/console-bot/train-nlp.js
> Fix console-bot example to have async train #77

- CONTRIBUTING.md
- [N/A] I have run `npm test` locally and all tests are passing.
Just minor documentation update
> doc: adding minor clarification to CONTRIBUTING.MD

- README.md
- package.json
Update emails and up to version 2.0.4
> build: version 2.0.4

- package.json
Generating version 2.1.0 including frontend bundle
> build: version 2.1.0

- lib/classifiers/bayes-classifier.js
- lib/classifiers/index.js
- lib/index.js
- test/classifiers/bayes-classifier.test.js
Added a simple [Naive Bayes Classifier](https://en.wikipedia.org/wiki/Naive_Bayes_classifier) class. It inherits from `Classifier` abstract class in the same way as `LogisticRegressionClassifier`.
Logistic regression classifier provides a great way to classify, but requires CPU intensive process to train.
A Bayes Classifier, on the other hand, don't need a CPU intensive process to train, so can grow in a progressive way without consuming time.
> feat: Add Naive Bayes Classifier

- README.md
> Change is in README...all checklist items are N/A
This change makes the example of use immediately executable when copy/pasted into `index.js` and run with `node index` (after installing dependencies).
Personally, I like it when I can copy/paste example code and run it without changes. This sort of behavior also punctuates the "ease" that is meant to be conveyed.
Take it or leave it. Great project! Thank you for sharing ;)
> docs: make example of use copy-and-paste-able

- lib/nlp/nlp-manager.js
- package-lock.json
Fix guesser when there is only one language.
> fix: Fix guesser.

- README.md
Replace promise "then" with async/await in Example of Use
> Change is in README.md --> all PR checklist items are "N/A"
Replace promise "then" with async/await in Example of Use. I know I just made a PR to update this...but after looking at it again, I thought it would make sense to go "all in" with the async/await syntax for this code example.
> Go "all in" with async/await syntax

- package-lock.json
- package.json
> Greenkeeper/brain.js 1.4.7

- package-lock.json
- package.json
Update dependencies to last versions.
> build: update dependencies to last versions

- docs/nlp-classifier.md
`classify` must have been renamed to `getBestClassification`. Fixing documentation.
> Fix method name

- docs/nlp-classifier.md
Fixed getter
https://github.com/axa-group/nlp.js/blob/5fd9e804d1a48dc56ad45b06e2f962c1233e7a7b/lib/classifiers/classifier.js#L152
https://github.com/axa-group/nlp.js/blob/defd0ffe8e69aaa845c6cf4b059c6077a084c55d/test/nlp/nlp-classifier.test.js#L231-L233
> Fixed getter

- docs/slot-filling.md
I have updated the example of slot filling because it has crossed questions in addSlot parameter and can confuse people.
> fix(docs): update slot filling example

- examples/console-bot/train-nlp.js
- lib/nlp/nlp-manager.js
The save to file now can be done minified. To understand the change in the size of files, the console-bot model generated was 928KB, after this change is 379KB with exactly same data.
> Save model to json minified

- lib/ner/constants.js
- lib/ner/ner-manager.js
- lib/ner/trim-named-entity.js
Added some trim constants to improve the code quality.
> chore(trim-types): add trim type constants

- lib/nlp/nlp-manager.js
- lib/nlu/domain-manager.js
- lib/nlu/nlu-manager.js
- test/nlu/domain-manager.test.js
Domain Name can be provided in NLP Manager process, or getClassifications at NLU Manager and Domain Manager.
> feat: domain name can be provided

- lib/nlp/nlp-manager.js
Fix https://github.com/axa-group/nlp.js/issues/201
> fix: Optional utterance not working.

- lib/classifiers/neural-network.js
- test/classifiers/neural-network.test.js
Improve neural network classifier performance, with an optimization when the calculated error is 0.
> perf: improve neural network perf

- lib/nlp/nlp-manager.js
- lib/nlu/base-nlu.js
- lib/nlu/brain-nlu.js
- lib/nlu/nlu-manager.js
- package-lock.json
- test/nlu/nlu-manager.test.js
Some small improvements and optional feature to avoid false positives.
> feat: have an option for better avoid of false positives

- lib/classifiers/neural-network.js
- lib/nlu/base-nlu.js
Reduce the generated model sizes when exporting to json/file
> reduce model size by erasing weights 0

- docs/loading-from-excel.md
*removed*
Just a doc typo fix.
... da. -> ... data.
> docs: loading-from-excel: fix a typo

- lib/language/language.js
- lib/ner/named-entity.js
- lib/nlu/nlu-manager.js
- lib/sentiment/sentiment-manager.js
- lib/util/helper.js
- lib/xtables/xtable.js
- package-lock.json
- package.json
Update dependencies to the last version
> feat: update dependencies

- lib/classifiers/neural-network.js
- lib/nlu/base-nlu.js
- lib/nlu/brain-nlu.js
- lib/util/helper.js
- test/classifiers/neural-network.test.js
Improve performance to be able to train huge datasets. Tested with 10k intents (all ok).
For more than 10k intents, node should be initialized with --max-old-space-size=4096
> feat: train huge datasets

- lib/nlp/nlp-util.js
- lib/nlp/stemmers/bengali-stemmer.js
- lib/nlp/tokenizers/aggresive-tokenizer-bn.js
- lib/nlp/tokenizers/index.js
- test/nlp/nlp-manager.test.js
- test/nlp/stemmers/bengali-stemmer.test.js
- test/nlp/tokenizers/aggresive-tokenizer-bn.test.js
> feat: Adding Bengali

- lib/nlp/nlp-util.js
- lib/nlp/stemmers/greek-stemmer.js
- lib/nlp/tokenizers/aggressive-tokenizer-el.js
- lib/nlp/tokenizers/index.js
- test/nlp/stemmers/greek-stemmer.test.js
> feat: adding greek support

- lib/util/handlebars.js
- test/util/handlebars.test.js
Add traverse to handlebars so it can process arrays and objects in deep.
Solves https://github.com/axa-group/nlp.js/issues/257
> feat: add traverse to handlebars to support arrays and objects.

- lib/util/similar-search.js
- test/util/similar_search.test.js
Faster levenshtein distance calculation (when not using collator). It pass from 700 ops/sec up to 300.000 ops/sec.
> feat: faster levenshtein

- README.md
> doc: add contributors to readme

- lib/nlu/nlu-manager.js
- [] I have added/updated tests for any new behavior.
Sort the get classifications result at the NLU manager before checking if is an equal classification.
> feat: sort classifications in the nlu manager

- package-lock.json
- package.json
Hi, thanks for the awesome module.
This adds the [uglifyify](https://github.com/hughsk/uglifyify) browserify transform to the `browserdist` script. It uses terser so it should resolve #269.
> Add uglifyify transform to browserdist script

- package-lock.json
- package.json
> fix: align packages

- examples/benchmark/corpus50es.json
- examples/benchmark/index.js
Add a benchmark with a corpus in spanish.
> feat: add spanish corpus benchmark

- lib/nlp/stemmers/spanish-stemmer.js
- test/nlp/stemmers/spanish-stemmer.test.js
Better spanish stemmer with among trees
> feat: build trees with the amongs for a better find backwards

- README.md
> fix spelling and grammar mistake

- docs/nlp-manager.md
- [N/A] I have run `npm test` locally and all tests are passing.
I found that the NLP Manager Transformers documentation was 
incorrect, using `transformer` instead of `processTransformer`. 
I updated the example to use the correct function, and added 
additional examples. 
While I was fixing that example, I thought I'd do an editing pass on the 
rest of the immediate content to correct some grammar, and add some 
details I thought would be useful based on my experience using this 
library. This may be at risk of breaking the "focused on a single change"
convention. I can divide the PR into smaller pieces of desired.
> docs: updates NLP Manager documentation

- README.md
- docs/language-support.md
> docs: add auto-stemmer documentation

- lib/nlp/stemmers/armenian-stemmer.js
- lib/nlp/stemmers/irish-stemmer.js
- lib/nlp/stemmers/slovene-stemmer.js
- lib/nlp/stemmers/tamil-stemmer.js
> fix: some stemmers have a duplicated stem method

- package-lock.json
- package.json
> build: version 3.10.1

- packages/similarity/src/leven.js
N/A
Removing one condition check on levenshtein inner loop by replacing it with a bitwise or on the boolean value, effectively converting it to 0 or 1. Disabled es-lint on this specific line as didn't understand the use of bitwise logic here.
> Removing one conditional on levenshtein inner loop

- docs/example-of-use.md
> fixed syntax error in documentation code

- lib/nlp/stemmers/czech-stemmer.js
> fix: stem method was duplicated

- examples/02-qna-classic/index.js
- examples/02-qna-classic/train-nlp.js
- examples/03-qna-pipelines/conf.json
- examples/03-qna-pipelines/corpus.json
- examples/03-qna-pipelines/index.js
- examples/03-qna-pipelines/pipelines.md
- packages/console-connector/.npmignore
- packages/console-connector/LICENSE.md
- packages/console-connector/README.md
- packages/console-connector/package.json
- packages/console-connector/src/console-connector.js
- packages/console-connector/src/index.js
- packages/core/src/container-bootstrap.js
- packages/core/src/container.js
- packages/core/src/default-compiler.js
- packages/nlp/src/nlp.js
- packages/nlu/src/domain-manager.js
Adding examples of QnA with old style and new style
> feat: examples of usage with qna

- examples/06-huge-ner/conf.json
- examples/06-huge-ner/corpus.json
- examples/06-huge-ner/index.js
- examples/06-huge-ner/pipelines.md
- packages/ner/src/extractor-enum.js
- packages/ner/src/ner.js
- packages/ner/src/reduce-edges.js
- packages/ner/test/extractor-enum.test.js
Fast Enum NER for threshold 1.
> feat: fast enum NER with threshold 1

- packages/core/src/container.js
- packages/nlp/test/nlp.test.js
- packages/python-compiler/src/python-compiler.js
- packages/python-compiler/test/python-compiler.test.js
> fix: removing comments from python

- packages/evaluator/src/javascript-compiler.js
- packages/nlp/src/nlp.js
Add event on intent and skill to run pipelines in javascript/python from other pipelines
> feat: adding event on intent

- packages/basic/src/index.js
- packages/core-loader/src/container-bootstrap.js
- packages/core/src/among.js
- packages/core/src/arr-to-obj.js
- packages/evaluator/src/javascript-compiler.js
- packages/nlp/src/nlp.js
Added javascript variable declaration
> feat: javascript variable declaration

- lib/classifiers/bayes-classifier.js
- test/nlu/bayes-nlu.test.js
The bayes classifier were having a weird behaviour, returning right coefficients but associating with wrong labels. It was fixed incrementing starting counter, and total classes smoothing coefficient.
> Fix bayes classifier

- README.md
- docs/v4/webandreact.md
- packages/core/src/container-bootstrap.js
- packages/core/src/default-compiler.js
- packages/core/src/mock-fs.js
- packages/request-rn/src/fs.js
- packages/request/src/fs.js
> docs: update docs web and react

- packages/express-api-server/src/express-api-server.js
- packages/nlu/src/nlu-neural.js
- packages/node-nlp/src/recognizer/conversation-context.js
- packages/node-nlp/src/recognizer/index.js
- packages/node-nlp/src/recognizer/memory-conversation-context.js
- packages/node-nlp/src/recognizer/recognizer.js
- packages/node-nlp/test/recognizer/conversation-context.test.js
- packages/node-nlp/test/recognizer/memory-conversation-context.test.js
Add Microsoft Bot Framework Recognizer
> feat: Add Recognizer

- packages/lang-zh/src/dictionary.js
> feat: lazy load cedict

- packages/lang-ko/src/korean-dictionary.js
- packages/lang-ko/src/korean-substantive.js
- packages/lang-ko/src/korean-tokenizer.js
- packages/lang-ko/src/stemmer-ko.js
Lazy load korean dictionaries and conjugations
> feat: lazy load korean

- packages/nlp/src/nlp.js
- packages/qna-importer/.npmignore
- packages/qna-importer/LICENSE.md
- packages/qna-importer/README.md
- packages/qna-importer/package.json
- packages/qna-importer/src/index.js
- packages/qna-importer/src/qna-importer.js
- packages/qna-importer/test/qna-importer.test.js
- packages/qna-importer/test/qna.tsv
QnA transformer that converts tsv/csv files into corpus/corpora
> feat: add QnA importer plugin

- packages/lang-fr/src/tokenizer-fr.js
- packages/lang-fr/test/tokenizer-fr.test.js
Replace default tokenizer for a custom tokenizer for french.
This solves https://github.com/axa-group/nlp.js/issues/420
> feat: fr tokenizer

- packages/node-nlp/test/sentiment/sentiment-manager.test.js
- packages/sentiment/src/sentiment-analyzer.js
Added correct stemming for sentiment analysis.
This fix https://github.com/axa-group/nlp.js/issues/409
> fix: sentiment stemmer

- packages/neural/src/neural-network.js
- packages/neural/test/neural-network.test.js
- packages/nlu/src/nlu-neural.js
- packages/nlu/src/nlu.js
- packages/nlu/test/nlu-neural.test.js
Know if the nlu setting returnExplanation is activated, it returns an explanation of the sentence indicating for each word the token, the stem and the weight.
> feat: neural network can explain results

- docs/v3/example-with-languages.md
Spelling correction for detected in comments
> spelling correction for detected

- examples/90-benchmark/corpus-en.json
- examples/90-benchmark/corpus-es.json
- examples/90-benchmark/index.js
Add a benchmark example to show performance with builtin entities and without builtint entities.
> feat: benchmark example

- docs/v3/language-guesser.md
- docs/v3/ner-manager.md
- docs/v3/static/Language.html
- docs/v3/static/NerManager.html
- docs/v3/static/NlpManager.html
- docs/v3/static/SimilarSearch.html
- docs/v3/static/language_language.js.html
- docs/v3/static/ner_ner-manager.js.html
- docs/v3/static/nlp_nlp-manager.js.html
- docs/v3/static/util_similar-search.js.html
- package-lock.json
- packages/builtin-microsoft/src/builtin-microsoft.js
- packages/language-min/src/language.js
- packages/language-min/test/language.test.js
- packages/language/src/language.js
- packages/language/test/language.test.js
- packages/nlu/src/nlu.js
- packages/node-nlp/test/language/language.test.js
- packages/node-nlp/test/util/similar_search.test.js.no
Changed white/black list for allow/deny list on source code and documentation
> Changing white/black list for allow/deny list

- packages/lang-fr/src/tokenizer-fr.js
- [] I have added/updated tests for any new behavior.
Improve the french tokenizer, split by apostrophe.
> fix: update tokenizer french to split by apostrophe

- examples/80-bert-server/README.md
- examples/80-bert-server/app.py
- examples/80-bert-server/corpus-en.json
- examples/80-bert-server/corpus-es.json
- examples/80-bert-server/index.js
- examples/80-bert-server/requirements.txt
An example of use of the BERT capabilities, including an example of BERT server with python
> feat: Benchmark example using BERT

- packages/lang-es/src/stemmer-es.js
Improve spanish stemmer for irregular verbs ended in z/c
> feat: improve spanish stemmer irregular z/c verbs

- packages/node-nlp/src/nlp/nlp-manager.js
Add a method to train and evaluate a corpus
> feat: method to train and evaluate a corpus

- packages/nlp/src/nlp.js
> feat: add domain corpora format

- packages/neural-worker/.npmignore
- packages/neural-worker/LICENSE.md
- packages/neural-worker/README.md
- packages/neural-worker/package.json
- packages/neural-worker/src/default-settings.json
- packages/neural-worker/src/helper.js
- packages/neural-worker/src/index.js
- packages/neural-worker/src/neural-network.js
- packages/neural-worker/src/worker.js
- packages/neural-worker/test/corpus.json
- packages/neural-worker/test/neural-network.test.js
- packages/nlu/src/nlu-neural.js
> feat: add a threaded training

- packages/neural-worker/src/neural-network.js
- packages/neural/src/neural-network.js
- packages/nlu/src/domain-manager.js
- packages/nlu/src/nlu.js
- packages/nlu/test/nlu-neural.test.js
Improve neural network explanation, include bias.
> feat: improve explanation

- packages/core-loader/src/plugin-information.json
- packages/database/.npmignore
- packages/database/LICENSE.md
- packages/database/README.md
- packages/database/package.json
- packages/database/src/collection.js
- packages/database/src/database.js
- packages/database/src/index.js
- packages/database/src/memory-adapter.js
- packages/database/test/collection.test.js
- packages/database/test/database.test.js
- packages/database/test/fs.js
- packages/database/test/memory-adapter.test.js
Add Database and Memory Database Adapter
> feat: Add Database and MemoryDB Adapter

- packages/mongodb-adapter/.npmignore
- packages/mongodb-adapter/LICENSE.md
- packages/mongodb-adapter/README.md
- packages/mongodb-adapter/package-lock.json
- packages/mongodb-adapter/package.json
- packages/mongodb-adapter/src/index.js
- packages/mongodb-adapter/src/mongodb-adapter.js
- packages/mongodb-adapter/test/collection-mock.js
- packages/mongodb-adapter/test/mongodb-adapter.test.js
- packages/mongodb-adapter/test/mongodb-mock.js
- packages/msbf-connector/package-lock.json
Add mongodb adapter for Database.
> feat: mongodb adapter

- packages/nlu-luis/src/nlu-luis.js
Add a corpus transformer to the LUIS nlu
> feat: add LUIS corpus transformer

- packages/utils/src/base-fn.js
- packages/utils/src/index.js
- packages/utils/src/markov.js
- packages/utils/test/markov.test.js
Add markov chains to the utils
> feat: markov chains

- packages/utils/package-lock.json
- packages/utils/package.json
- packages/utils/src/nlp-analyzer.js
- packages/utils/test/nlp-analyzer.test.js
Add analyzer that generates Confusion Matrix and other metrics
> feat: NLP analyzer

- packages/utils/src/index.js
- packages/utils/src/pattern.js
- packages/utils/test/corpus-composed.json
- packages/utils/test/corpus-pattern.json
- packages/utils/test/pattern.test.js
- Added cartesian product
- Compose strings from a pattern
- Transform a corpus with patterns to a final corpus
> feat: compose corpus from pattern strings

- packages/ner/src/ner.js
- packages/nlg/src/nlg-manager.js
- packages/nlu/src/domain-manager.js
- packages/nlu/src/nlu-manager.js
- packages/nlu/src/nlu.js
- packages/sentiment/src/sentiment-analyzer.js
Don't use pipelines if are the default ones.
> feat: improve performance

- examples/04-qna-web/corpus.json
- Update spelling mistakes in corpus.json file.
- Parth to file is below.
> https://github.com/axa-group/nlp.js/edit/master/examples/04-qna-web/corpus.json
> Update spelling mistakes in corpus.json file.

- packages/nlp/src/nlp.js
- packages/nlu/src/nlu-manager.js
- packages/node-nlp/src/nlp/nlp-manager.js
- packages/node-nlp/test/nlp/nlp-manager.test.js
Add methods to remove languages
> feat: allow language removal

- examples/06-huge-ner/conf.json
- packages/bert-tokenizer/src/bert-word-piece-tokenizer.js
- packages/bert-tokenizer/src/multi-bert-word-piece-tokenizer.js
- packages/nlp/src/nlp.js
Add a forceNER setting to NLP to force NER calculations on process
> feat: NLP new setting forceNER

- packages/utils/src/corpus-lookup.js
- packages/utils/src/index.js
- packages/utils/src/lookup.js
- packages/utils/test/corpus-lookup.test.js
- packages/utils/test/lookup.test.js
Add the lookup and Corpus Lookup to help build custom classifiers.
> feat: add Lookup and Corpus Lookup to Utils

- packages/utils/src/bench.js
- packages/utils/src/index.js
- packages/utils/test/bench.test.js
Add a Bench class to the utils so Benchmarks between classifiers can be done
> feat: Add Bench class

- packages/bot-manager/package-lock.json
- packages/lang-ja/package-lock.json
- packages/mongodb-adapter/package-lock.json
- packages/msbf-connector/package-lock.json
- packages/similarity/src/spell-check.js
- packages/similarity/test/spell-check.test.js
- packages/utils/package-lock.json
- packages/utils/test/corpus-lookup.test.js
- packages/utils/test/lookup.test.js
SpellCheck improvements:
- Get best word by frequency
- Set default distance to 1
> feat: improve spell check

- packages/ner/src/ner.js
- packages/ner/test/extractor-enum.test.js
- packages/ner/test/extractor-regex.test.js
- packages/ner/test/extractor-trim.test.js
Add default extractors to the NER container if they don't exists
> feat: default NER extractors

- package-lock.json
- package.json
- packages/builtin-microsoft/test/builtin-microsoft.test.js
Bump eslint-plugin-jest from 23.20.0 to 24.0.0
> build(deps-dev): bump eslint-plugin-jest from 23.20.0 to 24.0.0

- packages/directline-connector/src/directline-controller.js
- packages/nlp/src/nlp.js
- packages/nlp/test/nlp.test.js
Hi @jesus-seijas-sp,
* Status :~ __READY__;
Just the changes to single lines in two files, as discussed in #546.
I'll investigate whether I can add any additional unit tests for the `nlp` package.
Yours,
Nick
> feat: Add the user's ID (from.id) to the input for plugins (#546)

- packages/core-loader/src/dock.js
- packages/core/src/container-bootstrap.js
- packages/core/src/container.js
- packages/core/src/context.js
- packages/core/src/dock.js
- packages/core/src/memory-storage.js
- packages/database/src/database.js
- packages/database/src/memory-adapter.js
- packages/directline-connector/src/directline-connector.js
- packages/express-api-server/src/express-api-server.js
- packages/express-api-serverless/src/express-api-serverless.js
- packages/lang-bn/src/normalizer-bn.js
- packages/lang-ko/src/korean-chunker.js
- packages/lang-zh/src/translate-zh.js
- packages/mongodb-adapter/src/mongodb-adapter.js
- packages/msbf-connector/src/msbf-connector.js
- packages/ner/src/extractor-enum.js
- packages/ner/src/ner.js
- packages/python-compiler/src/python-executer.js
- packages/similarity/src/spell-check.js
> fix: remove tech debt in dock and spell check

- packages/nlp/src/nlp.js
- [] I have added/updated tests for any new behavior.
Add entities to the context so can be used in NLG
> feat: put entities into context

- package-lock.json
- packages/directline-connector/package-lock.json
- packages/directline-connector/package.json
- packages/directline-connector/src/directline-controller.js
Replace  isomorphic-fetch with node-fetch
> fix: remove isomorphic fetch

- packages/nlg/src/nlg-manager.js
- packages/nlg/test/nlg-manager.test.js
Fix pattern generation in NLG.
Example of pattern: "(Hello|hi) user"
> fix: NLP patterns was broken

- packages/logger/README.md
> docs: add TOC to logger readme

- packages/core-loader/src/plugin-information.json
- packages/express-api-server/package-lock.json
Fix typo in tagalog language plugin information
> fix: plugin information for tagalog language has a type

- packages/directline-connector/src/directline-controller.js
- packages/nlp/src/context-manager.js
- packages/nlp/src/index.js
- packages/nlp/test/context-manager.test.js
Add ContextManager that will be added to container by Nlp class, to obtain automatic integration with context
> feat: Add Context Manager

- packages/nlp/src/context-manager.js
- packages/nlp/src/nlp.js
- packages/nlp/test/nlp.test.js
NLP class now register ContextManager into container and use it to load and save context.
> fix: add Context Manager to NLP

- packages/similarity-wa/src/spell-check.js
Fixing SonarQube TypeError issue and bringing spell-check on `similarity-wa` package up-to-date with `similarity` package.
> fix: SonarQube TypeError issue

- packages/nlp/src/nlp.js
Add data to context manager from corpus.
> feat: Context data loading for nlp from corpus

- packages/nlp/src/context-manager.js
- packages/nlp/test/context-manager.test.js
Fix the problem when saving into mongodb with id not compatible
> fix: error in conversation id when saving into database

- package.json
Remove silent option from jest
> feat: remove silent from jest options

- package.json
> build: reactivate silent mode for jest

- examples/13-languages/english/12-benchmark.js
- examples/13-languages/english/corpus-en.json
- examples/13-languages/measure-corpus.js
Benchmark example for english language
> docs: add benchmark for english

- examples/13-languages/measure-corpus.js
Make language examples to measure using 0 and 0.5 threshold values on NLP.
> docs: measure corpus use NLP threshold

- README.md
I noticed some grammar and language issues, so thought I'd try to make the document clearer.
I hope this helps.
Yours,
Nick
> fix: language and grammar in the root README

- README.md
- docs/v4/language-support.md
- examples/13-languages/corpora/corpus-id.json
- examples/13-languages/indonesian/01-normalization.js
- examples/13-languages/indonesian/02-tokenization.js
- examples/13-languages/indonesian/03-tokenization-normalized.js
- examples/13-languages/indonesian/04-stopword-identify.js
- examples/13-languages/indonesian/05-stopword-remove.js
- examples/13-languages/indonesian/06-stopword-dictionary.js
- examples/13-languages/indonesian/07-stem-word.js
- examples/13-languages/indonesian/08-stem-array.js
- examples/13-languages/indonesian/09-tokenize-and-stem.js
- examples/13-languages/indonesian/10-tokenize-and-stem-remove-stopwords.js
- examples/13-languages/indonesian/11-sentiment-analysis.js
- examples/13-languages/indonesian/12-benchmark.js
- packages/lang-id/README.md
> docs: document indonesian language

- docs/v3/nlp-manager.md
> Expand documentation on autoSave setting

- examples/14-ner-corpus/README.md
- examples/14-ner-corpus/conf.json
- examples/14-ner-corpus/corpus.json
- examples/14-ner-corpus/heros.json
- examples/14-ner-corpus/index.js
- examples/14-ner-corpus/pipelines.md
Example of NER corpus loading.
> docs: document NER corpus loading with an example

- packages/nlp/src/nlp.js
- packages/nlp/test/nlp.test.js
- packages/node-nlp/src/nlp/nlp-manager.js
- packages/node-nlp/test/nlp/nlp-manager.test.js
> docs: unit tests for NER trim

- packages/ner/src/reduce-edges.js
- packages/ner/test/reduce-edges.test.js
> tests: add tests for reduce edges

- packages/node-nlp/test/nlp/nlp-manager.test.js
> fix: remove duplications of nlp manager

- packages/ner/README.md
- packages/ner/src/extractor-enum.js
- packages/ner/test/extractor-enum.test.js
When exact enum extracting, don't lowcase sources.
> fix: in exact enum extraction, source text is now not normalized

- packages/builtin-microsoft/src/builtin-microsoft.js
- packages/ner/src/reduce-edges.js
> fix: builtin entity duplicity

- packages/nlu/src/domain-manager.js
- packages/nlu/src/nlu.js
- packages/nlu/test/domain-manager.test.js
- packages/nlu/test/nlu-manager.test.js
- packages/nlu/test/nlu-neural.test.js
- packages/node-nlp/src/nlp/nlp-manager.js
- packages/node-nlp/test/nlp/corpus-en.json
- packages/node-nlp/test/nlp/nlp-manager.test.js
> feat: intent allow list in nlp

- packages/bot/.npmignore
- packages/bot/LICENSE.md
- packages/bot/README.md
- packages/bot/package-lock.json
- packages/bot/package.json
- packages/bot/src/bot.js
- packages/bot/src/dialog-manager.js
- packages/bot/src/dialog-parse.js
- packages/bot/src/index.js
- packages/connector/.npmignore
- packages/connector/LICENSE.md
- packages/connector/README.md
- packages/connector/package.json
- packages/connector/src/connector.js
- packages/connector/src/index.js
- packages/connector/src/session.js
- packages/connector/test/connector.test.js
- packages/console-connector/src/console-connector.js
- packages/core-loader/src/plugin-information.json
- packages/directline-connector/package.json
- packages/directline-connector/src/directline-connector.js
- packages/directline-connector/src/directline-controller.js
- packages/lang-bert/src/tokenizer-bert.js
- packages/nlu/src/domain-manager.js
- packages/open-question/src/qa-client.js
- packages/open-question/src/runtime-thread.js
- packages/request/test/file.txt
- packages/request/test/fs.test.js
First approach of adding a bot plugin to make transactional chats
> feat: adding bot

- packages/bot/package.json
- packages/bot/src/bot.js
- packages/bot/src/dialog-manager.js
- packages/bot/src/index.js
- packages/bot/src/test-connector.js
- packages/bot/test/bot.test.js
- packages/bot/test/script1.dlg
- packages/bot/test/script2.dlg
- packages/connector/src/session.js
- packages/express-api-server/package-lock.json
Adding TestConnector for testing bots
> feat: TestConnector

- packages/bot/src/test-connector.js
- packages/bot/test/bot.test.js
- packages/bot/test/mock-template.js
- packages/bot/test/scenario01.dlt
Add TestConnector run scenarios
> feat: TestConnector to run scenarios

- packages/bot/src/bot.js
- packages/bot/src/dialog-parse.js
- packages/bot/test/bot.test.js
- packages/bot/test/scenario01.dlt
- packages/bot/test/script1.dlg
> feat: bot actions

- docs/v3/static/styles/prettify-tomorrow.css
- examples/01-container/index.js
- packages/lang-sr/src/stemmer-sr.js
Improvements to code readability and quality gate.
Example:
From    !(this.I_p1 == this.I_p2)
To          (this.I_p1 !== this.I_p2)
> A few code quality improvements based on the Quality Gate rules

- packages/bot/src/bot.js
- packages/bot/src/dialog-parse.js
- packages/bot/test/bot.test.js
- packages/bot/test/mock-template.js
- packages/bot/test/script3.dlg
Add corpus load from new dialog format
> feat: bot load corpus

- packages/bot/src/bot.js
Add context data loading from .dlg
> feat: bot load context data from dlg.

- packages/bot/src/bot.js
- packages/bot/src/dialog-parse.js
- packages/bot/src/test-connector.js
- packages/bot/test/mock-template.js
- packages/connector/src/session.js
- packages/console-connector/src/console-connector.js
- packages/directline-connector/src/directline-connector.js
> feat: add suggested actions

- packages/bot/src/bot.js
When a card has inputs, values are retrieved and stored as context variables by the input id.
> feat: bot extract context variables from card values

- packages/bot/src/bot.js
- packages/bot/src/dialog-manager.js
- packages/connector/src/session.js
Bot validators and restart command
> feat: bot validators and restart flows

- packages/builtin-microsoft/src/builtin-microsoft.js
Builtins can be defined by input object
> feat: builtin list can be provided by input object

- packages/bot/src/bot-localization.js
- packages/bot/src/bot.js
- packages/bot/test/bot.test.js
- packages/bot/test/scenario02.dlt
- packages/bot/test/script4.dlg
- packages/connector/src/session.js
- packages/express-api-server/src/express-api-server.js
- packages/fullbot/.npmignore
- packages/fullbot/LICENSE.md
- packages/fullbot/README.md
- packages/fullbot/package-lock.json
- packages/fullbot/package.json
- packages/fullbot/src/fullbot.js
- packages/fullbot/src/index.js
- packages/fullbot/test/fullbot.test.js
- packages/fullbot/test/script.dlg
FullBot for creating backend bots with preinstalled plugins.
Multilanguage for bots.
> feat: fullbot and multilanguage

- packages/dialogflow-connector/.npmignore
- packages/dialogflow-connector/LICENSE.md
- packages/dialogflow-connector/README.md
- packages/dialogflow-connector/package-lock.json
- packages/dialogflow-connector/package.json
- packages/dialogflow-connector/src/dialogflow-connector.js
- packages/dialogflow-connector/src/index.js
> feat: dialogflow connector

- packages/nlp/src/context-manager.js
> fix: context manager was creating several contexts per session

- packages/utils/src/index.js
- packages/utils/src/is-gibberish.js
- packages/utils/test/gibberish.test.js
> feat: gibberish detection

- packages/bot/src/bot.js
- packages/fullbot/package-lock.json
- packages/fullbot/package.json
- packages/fullbot/src/fullbot.js
- packages/fullbot/src/utils.js
- packages/nlp/src/context-manager.js
- packages/nlu/src/nlu.js
- packages/nlu/test/nlu-neural.test.js
- packages/nlu/test/nlu.test.js
- packages/node-nlp/test/nlp/nlp-manager.test.js
- packages/node-nlp/test/nlu/brain-nlu.test.js
- packages/slot/src/slot-manager.js
Remove automatic useNoneFeature (now is false by default)
Remove useNoneFeature by language
Add mount and backup methods for fullbot
Fix **slot.isEmpty** when loading a saved model.
> feat: add fullbot mount method

- packages/dialogflow-connector/src/dialogflow-connector.js
- packages/rest-connector/.npmignore
- packages/rest-connector/LICENSE.md
- packages/rest-connector/README.md
- packages/rest-connector/package.json
- packages/rest-connector/src/index.js
- packages/rest-connector/src/rest-connector.js
> feat: rest connector

- packages/nlp/src/context-manager.js
When saving to database, it was using as key the conversationId. This is not good for some engines where id at database must follow a given pattern.
Also, sometimes two entries at database where created, because the setContext is called twice with context without id. So right now, if the context has not id, then we retrieve from database context with same conversationId, to avoid creating duplicated entries in database for the same conversationId.
> fix: when saving context into database, key can be wrong.

- packages/bot/src/bot.js
Fix regex loading at bot scripts.
> fix: regex entities where not loaded correctly

- packages/rest-connector/src/rest-connector.js
Add request at session of REST connector.
> feat: add request on session at REST connector

- packages/bot/src/bot.js
Set default validation retries to 2
> fix: set default validation retries to 2

- packages/bot/src/validators.js
Accept builtins array in validator
> feat: accept builtins array for validator

- packages/bot/src/bot.js
- packages/nlu/src/domain-manager.js
- packages/nlu/src/nlu.js
- packages/nlu/test/nlu-neural.test.js
Fix allowed intents at DomainManager level.
Now allowed intents can contain wildchars.
> feat: allowed intents

- packages/lang-uk/src/stemmer-uk.js
- packages/lang-uk/test/stemmer-uk.test.js
- packages/open-question/package-lock.json
Ukranian stemmer without lookbehind regex
> fix: stemmer uk with no lookbehinds

- packages/msbf-connector/package-lock.json
- packages/msbf-connector/package.json
- packages/msbf-connector/src/get-msbf-token.js
- packages/msbf-connector/src/msbf-connector.js
Added extra endpoint to be used by any msbf client, to avoid exposing secret in frontend. Useful together with https://github.com/axa-group/nlp.js/pull/847
> feat: add msbf endpoint to generate token

- package-lock.json
- packages/express-api-server/src/express-api-app.js
- packages/msbf-connector/package.json
- packages/msbf-connector/src/get-msbf-token.js
- packages/open-question/package-lock.json
Remove package @nlpjs/basic from @nlpjs/msbf-connector
> fix: remove @nlpjs/basic from msbf connector

- packages/msbf-connector/package-lock.json
- packages/msbf-connector/package.json
- packages/msbf-connector/src/msbf-connector.js
Add flows management to Microsoft Bot Framework connector 🎉 
Before this PR msbf connector only worked in Q&A mode, now it's possible to generate conversational flows, also using adaptive cards.
Working with suggestions:
After selecting:
Example of carousel card:
> feat: add flows management to msbf connector

- packages/fb-connector/.npmignore
- packages/fb-connector/LICENSE.md
- packages/fb-connector/README.md
- packages/fb-connector/package-lock.json
- packages/fb-connector/package.json
- packages/fb-connector/src/fb-connector.js
- packages/fb-connector/src/index.js
- packages/fb-connector/src/settings.js
Added connector to facilitate the process of creating Facebook Messenger bots. Can work together with our nlp + conversational flows. More details are explained in README.md
Compatible with complex cards (carousel, ...)
> feat: add fb-connector module

- docs/v4/console-connector.md
- docs/v4/core/arr-to-obj.md
- docs/v4/core/file-system.md
- docs/v4/core/logger.md
- docs/v4/core/normalizer.md
- docs/v4/core/obj-to-arr.md
- docs/v4/core/stopwords.md
- docs/v4/core/timer.md
- docs/v4/core/uuid.md
- docs/v4/emoji.md
- docs/v4/language-support.md
- docs/v4/logger.md
- docs/v4/ner-quickstart.md
- docs/v4/neural.md
- docs/v4/nlu.md
- docs/v4/qna.md
- docs/v4/quickstart.md
- docs/v4/similarity.md
- docs/v4/webandreact.md
I have only edited v4 doc files, so no code changes or testing has been done.
1 - Modified a few doc files just to slightly improve the English.
2 - Some additional changes have not made due to my uncertainty include...
to show that NLP will work even with language support
Perhaps should be
to show that NLP will work even without language support
but with an option to normalize both texts between calculation
Perhaps should be
but with an option to normalize both texts before calculation
SpellCheck trained with words trained from a text
Perhaps should be
SpellCheck trained with words taken from a text
> Doc editing

- packages/core/src/tokenizer.js
- packages/lang-en-min/src/tokenizer-en.js
- packages/lang-en-min/test/tokenizer-en.test.js
Fixes #943 
Found a second location that failed (though did not throw an error) for a similar reason in `tokenizer.js`, fixed that as well.
> fix: errors when tokenizing 'constructor'

- examples/12-similarity/09-similarity-benchmark.js
- examples/12-similarity/README.md
Fix incomplete documentation of similarity examples. Added description and fixed variable names of _leven_ function benchmark example.
> doc: improved similarity example documentation

- CODE_OF_CONDUCT.md
Update code of conduct to use version 2.0 of the code of conduct from https://www.contributor-covenant.org
> chore: update code of conduct to 2.0

- packages/ner/src/ner.js
- packages/nlp/test/nlp.test.js
As explained in https://github.com/axa-group/nlp.js/issues/1007 removeNerRule doesn't worked well. Object detection was added to stringify properly that case inside asString method.
Closes #1007
> fix: update object detection

- packages/bot/src/bot.js
- packages/bot/src/helper.js
- packages/bot/src/test-connector.js
- packages/bot/test/helper.test.js
Improved test connector to be able to test real bots. Tested intents with multiple answers, dynamic answers & using adaptive cards.
> feat: improve test connector

- docs/v4/quickstart.md
This PR just fixes a minor documentation error. Fixed "compilar" to "compiler" & capitalized JavaScript properly.
> Minor documentation fix

- docs/v4/languages.md
The languages.md file is currently a blank file and has been since 2020. I suspect this file was created to put language support details in but language-support.md already accomplishes this task.
- [YES] I have run `npm test` locally and all tests are passing.
- [YES] I have added/updated tests for any new behavior.
- [YES] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here]
The languages.md file is currently a blank file and has been since 2020. I suspect this file was created to put language support details in but language-support.md already accomplishes this task. I am proposing the languages.md file be deleted since it serves no purpose and adds confusion.
> Fix: Delete languages.md

- examples/13-languages/corpora/corpus-fr.json
- examples/13-languages/french/01-normalization.js
- examples/13-languages/french/02-tokenization.js
- examples/13-languages/french/03-tokenization-normalized.js
- examples/13-languages/french/04-stopword-identify.js
- examples/13-languages/french/05-stopword-remove.js
- examples/13-languages/french/06-stopword-dictionary.js
- examples/13-languages/french/07-stem-word.js
- examples/13-languages/french/08-stem-array.js
- examples/13-languages/french/09-tokenize-and-stem.js
- examples/13-languages/french/10-tokenize-and-stem-remove-stopwords.js
- examples/13-languages/french/11-sentiment-analysis.js
- examples/13-languages/french/12-benchmark.js
- examples/13-languages/french/README.md
The main goal for this pull request is to add the examples in the french language.
> feat: french examples

- packages/builtin-duckling/src/builtin-duckling.js
- packages/builtin-duckling/test/duckling.test.js
- packages/builtin-microsoft/src/builtin-microsoft.js
- packages/builtin-microsoft/test/builtin-microsoft.test.js
This PR is fixing an obvious typo and also make sure that the entityName which is adjusted in code is also used in the returned entity. Formerly the "Microsoft style" entitiy name was rturned whoch do not match to the one expected by nlp.js
> fix: fix typos and issues in microsoft builtin

- packages/express-api-server/src/express-api-server.js
If settings 'key' and 'cert' are provided for the ExpressApiServer component (i.e.: under key 'api-server') and both files exists, the ExpressApiServer will try to use them to start and https server.
See nodejs [https.createServer([options][, requestListener])](https://nodejs.org/api/https.html#httpscreateserveroptions-requestlistener) for more details.
> feat: provide support for https

- packages/nlp/test/nlp.test.js
- packages/slot/src/slot-manager.js
- packages/slot/test/slot-manager.test.js
fixes https://github.com/axa-group/nlp.js/issues/1252
> fix: Fix crash on initial slot fill without a former question asked
